#### Introduction: 
Coronavirus disease (COVID-19) is an  PANDEMIC infectious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS‑CoV‑2). This new virus and disease were unknown before the outbreak began in Wuhan, China, in December 2019. COVID-19 is a pandemic affecting many countries globally.The time between exposure to COVID-19 and the moment when symptoms start is commonly around five to six days but can range from 1 – 14 days. I have gathered Covid-19 data from different sources. Dataset contains confirmed case, deaths and recovered cases, new active cases in world and in India and indian  State/UnionTerritory separately.

 * Coronavirus Analysis based on Confirmed, Dead and Recovered Patients all over World.
 * Second Analysis based on Deaths & Recovered Patient in India and its States and Union territories.
 * Analysis based on State Testing. 
 * Analysis based on Time series.

In [27]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns
from timeit import default_timer as timer
#from lxml import html 
#import re
import requests
import json

In [11]:
import matplotlib.ticker as ticker
import statsmodels.api as sm
import statsmodels.formula.api as smf
import plotly.express as px
import datetime
from plotly.subplots import make_subplots
import requests
from bs4 import BeautifulSoup 
import plotly.io as pio
from pandas.io.json import json_normalize
pio.renderers.default='notebook'

### Covid-19 data gathered from different sources:
    1. On the basis of all countries: data scraped using beautiful soup https://www.worldometers.info/coronavirus/
    2. Covid analysis of India:'covid_19_india.csv'    
    3. Analysis based on Age:'AgeGroupDetails.csv'
    4. Analysis based on ICMR Testing labs:'ICMRTestingDetails.csv'from    
    5. Analysis based on testing done in indian states:'StatewiseTestingDetails.csv' https://www.kaggle.com/sudalairajkumar/covid19-in-india
    6. Analysis based on Time Series Confirmed cases all over world from :
    7. Analysis based on Time Series Recovered case all over world:'time_series_covid19_recovered.csv'.
    8. Analysis based on Time Series Deaths case all over world:'time_series_covid19_deaths.csv'
    https://data.humdata.org/dataset/5dff64bc-a671-48da-aa87-2ca40d7abf02

### Covid_19 All countries scraped using beautiful soup from worldometers.com: 
    
    * The coronavirus COVID-19 is affecting 212 countries and territories around the world and 2 international conveyances data.
    
        - Total_cases
        - Total_deaths
        - Total_Recovered
        - New_cases
        - New Deaths
        - Active_Cases
        - Serious_Case
        - TotCases/1Mpop
        - Deaths/1Mpop
        - Total Tests
        - Test/1Mpop

In [3]:
url = "https://www.worldometers.info/coronavirus/" 
req_data = requests.get(url)
soup = BeautifulSoup(req_data.text, 'html.parser') 

# x = soup.findAll("tbody")
# if x is not None and len(x) > 0:
#     section = x[0]

table = soup.find('table', attrs={'id': 'main_table_countries_today'})
header = [col_name.text.rstrip('\n').strip() for col_name in table.select('thead th')]
table_rows = table.find_all('tr')
data = []
for tr in table_rows:
    try: 
        td = tr.find_all('td')
        row = [tr.text for tr in td]
        print(row) 
        data.append(row)
        full_data = pd.read_html(str(table))[0]
    except requests.Response.raise_for_status() as e:
        print("Error: Invalid Response Error.")

[]
['\nNorth America\n', '1,229,885', '+4,930', '72,032', '+252', '201,020', '956,833', '17,724', '', '', '', '', 'North America']
['\nEurope\n', '1,415,503', '+16,813', '138,018', '+609', '528,830', '748,655', '17,831', '', '', '', '', 'Europe']
['\nAsia\n', '540,122', '+6,281', '19,123', '+162', '278,344', '242,655', '5,534', '', '', '', '', 'Asia']
['\nSouth America\n', '190,749', '+650', '9,512', '+32', '63,943', '117,294', '9,816', '', '', '', '', 'South America']
['\nOceania\n', '8,370', '+22', '113', '+1', '7,134', '1,123', '30', '', '', '', '', 'Australia/Oceania']
['\nAfrica\n', '41,817', '+377', '1,700', '+9', '14,138', '25,979', '126', '', '', '', '', 'Africa']
['\n\n', '721', '', '15', '', '645', '61', '4', '', '', '', '', '']
['World', '3,427,167', '+29,073', '240,513', '+1,065', '1,094,054', '2,092,600', '51,065', '440', '30.9', '', '', 'All']
['USA', '1,134,084', '+3,054', '65,888 ', '+135', '161,782', '906,414', '16,481', '3,426', '199', '6,715,433', '20,288', 'North America']
['Spain', '245,567', '+2,588', '25,100 ', '+276', '146,233', '74,234', '2,386', '5,252', '537', '1,528,833', '32,699', 'Europe']
['Italy', '207,428', '', '28,236 ', '', '78,249', '100,943', '1,578', '3,431', '467', '2,053,425', '33,962', 'Europe']
['UK', '177,454', '', '27,510 ', '', 'N/A', '149,600', '1,559', '2,614', '405', '1,023,824', '15,082', 'Europe']
['France', '167,346', '', '24,594 ', '', '50,212', '92,540', '3,878', '2,564', '377', '1,100,228', '16,856', 'Europe']
['Germany', '164,271', '+194', '6,736 ', '', '129,000', '28,535', '2,189', '1,961', '80', '2,547,052', '30,400', 'Europe']
['Russia', '124,054', '+9,623', '1,222 ', '+53', '15,013', '107,819', '2,300', '850', '8', '3,945,518', '27,036', 'Europe']
['Turkey', '122,392', '', '3,258 ', '', '53,808', '65,326', '1,480', '1,451', '39', '1,075,048', '12,747', 'Asia']
['Iran', '96,448', '+802', '6,156 ', '+65', '77,350', '12,942', '2,787', '1,148', '73', '484,541', '5,769', 'Asia']
['Brazil', '92,630', '+521', '6,434 ', '+24', '38,039', '48,157', '8,318', '436', '30', '339,552', '1,597', 'South America']
['Canada', '55,061', '', '3,391 ', '', '22,751', '28,919', '557', '1,459', '90', '832,222', '22,050', 'North America']
['Belgium', '49,517', '+485', '7,765 ', '+62', '12,211', '29,541', '689', '4,273', '670', '260,996', '22,520', 'Europe']
['Peru', '40,459', '', '1,124 ', '', '11,129', '28,206', '658', '1,227', '34', '342,498', '10,388', 'South America']
['Netherlands', '40,236', '+445', '4,987 ', '+94', 'N/A', '34,999', '708', '2,348', '291', '225,899', '13,184', 'Europe']
['India', '37,336', '+79', '1,223 ', '', '10,007', '26,106', '', '27', '0.9', '976,363', '708', 'Asia']
['Switzerland', '29,817', '+112', '1,754 ', '', '23,900', '4,163', '141', '3,445', '203', '276,000', '31,890', 'Europe']
['Ecuador', '26,336', '', '1,063 ', '', '1,913', '23,360', '149', '1,493', '60', '71,950', '4,078', 'South America']
['Saudi Arabia', '25,459', '+1,362', '176 ', '+7', '3,765', '21,518', '139', '731', '5', '339,775', '9,760', 'Asia']
['Portugal', '25,190', '+203', '1,023 ', '+16', '1,671', '22,496', '150', '2,470', '100', '426,836', '41,860', 'Europe']
['Sweden', '22,082', '+562', '2,669 ', '+16', '1,005', '18,408', '531', '2,186', '264', '119,500', '11,833', 'Europe']
['Ireland', '20,833', '', '1,265 ', '', '13,386', '6,182', '123', '4,219', '256', '153,954', '31,179', 'Europe']
['Mexico', '20,739', '+1,515', '1,972 ', '+113', '12,377', '6,390', '378', '161', '15', '91,188', '707', 'North America']
['Pakistan', '18,770', '+678', '432 ', '+15', '4,753', '13,585', '111', '85', '2', '193,859', '878', 'Asia']
['Singapore', '17,548', '+447', '16 ', '', '1,268', '16,264', '23', '2,999', '3', '143,919', '24,600', 'Asia']
['Chile', '17,008', '', '234 ', '', '9,018', '7,756', '392', '890', '12', '189,433', '9,910', 'South America']
['Israel', '16,152', '+51', '227 ', '+2', '9,400', '6,525', '107', '1,866', '26', '390,022', '45,060', 'Asia']
['Belarus', '15,828', '+911', '97 ', '+4', '3,117', '12,614', '92', '1,675', '10', '195,430', '20,682', 'Europe']
['Austria', '15,558', '+27', '596 ', '+7', '13,180', '1,782', '114', '1,727', '66', '269,619', '29,936', 'Europe']
['Qatar', '14,872', '+776', '12 ', '', '1,534', '13,326', '72', '5,162', '4', '101,728', '35,309', 'Asia']
['Japan', '14,305', '', '455 ', '', '2,975', '10,875', '328', '113', '4', '174,150', '1,377', 'Asia']
['Poland', '13,375', '+270', '664 ', '+13', '3,762', '8,949', '160', '353', '18', '366,013', '9,671', 'Europe']
['UAE', '13,038', '', '111 ', '', '2,543', '10,384', '1', '1,318', '11', '1,200,000', '121,330', 'Asia']
['Romania', '12,732', '+165', '755 ', '+11', '4,547', '7,430', '265', '662', '39', '190,540', '9,905', 'Europe']
['Ukraine', '11,411', '+550', '279 ', '+7', '1,498', '9,634', '151', '261', '6', '122,752', '2,807', 'Europe']
['Indonesia', '10,843', '+292', '831 ', '+31', '1,665', '8,347', '', '40', '3', '107,943', '395', 'Asia']
['S. Korea', '10,780', '+6', '250 ', '+2', '9,123', '1,407', '55', '210', '5', '623,069', '12,153', 'Asia']
['Denmark', '9,407', '+96', '475 ', '+15', '6,889', '2,043', '60', '1,624', '82', '221,912', '38,312', 'Europe']
['Serbia', '9,362', '+157', '189 ', '+4', '1,426', '7,747', '65', '1,071', '22', '96,637', '11,060', 'Europe']
['Philippines', '8,928', '+156', '603 ', '+24', '1,124', '7,201', '31', '81', '6', '115,012', '1,050', 'Asia']
['Bangladesh', '8,790', '+552', '175 ', '+5', '177', '8,438', '1', '53', '1', '76,066', '462', 'Asia']
['Norway', '7,783', '', '210 ', '', '32', '7,541', '37', '1,436', '39', '172,586', '31,835', 'Europe']
['Czechia', '7,740', '+3', '241 ', '+1', '3,378', '4,121', '67', '723', '23', '253,826', '23,702', 'Europe']
['Dominican Republic', '7,288', '', '313 ', '', '1,387', '5,588', '144', '672', '29', '25,368', '2,339', 'North America']
['Colombia', '7,006', '', '314 ', '', '1,551', '5,141', '118', '138', '6', '108,950', '2,141', 'South America']
['Australia', '6,783', '+16', '93 ', '', '5,789', '901', '28', '266', '4', '611,583', '23,984', 'Australia/Oceania']
['Panama', '6,720', '+188', '192 ', '+4', '622', '5,906', '85', '1,557', '44', '31,895', '7,392', 'North America']
['Malaysia', '6,176', '+105', '103 ', '', '4,326', '1,747', '31', '191', '3', '184,213', '5,692', 'Asia']
['South Africa', '5,951', '', '116 ', '', '2,382', '3,453', '36', '100', '2', '217,522', '3,668', 'Africa']
['Egypt', '5,895', '', '406 ', '', '1,460', '4,029', '', '58', '4', '90,000', '879', 'Africa']
['Finland', '5,176', '+125', '220 ', '+2', '3,000', '1,956', '52', '934', '40', '101,800', '18,373', 'Europe']
['Morocco', '4,687', '+118', '172 ', '+1', '1,235', '3,280', '1', '127', '5', '38,102', '1,032', 'Africa']
['Kuwait', '4,619', '+242', '33 ', '+3', '1,703', '2,883', '69', '1,082', '8', '179,000', '41,915', 'Asia']
['Argentina', '4,532', '', '229 ', '+4', '1,320', '2,983', '157', '100', '5', '61,530', '1,361', 'South America']
['Algeria', '4,154', '', '453 ', '', '1,821', '1,880', '22', '95', '10', '6,500', '148', 'Africa']
['Moldova', '4,052', '+72', '124 ', '+2', '1,334', '2,594', '237', '1,004', '31', '11,763', '2,916', 'Europe']
['Luxembourg', '3,802', '', '92 ', '', '3,213', '497', '23', '6,074', '147', '44,895', '71,720', 'Europe']
['Kazakhstan', '3,800', '+203', '25 ', '', '985', '2,790', '41', '202', '1', '282,862', '15,065', 'Asia']
['Bahrain', '3,273', '+103', '8 ', '', '1,567', '1,698', '1', '1,924', '5', '138,278', '81,265', 'Asia']
['Thailand', '2,966', '+6', '54 ', '', '2,732', '180', '61', '42', '0.8', '178,083', '2,551', 'Asia']
['Hungary', '2,942', '+79', '335 ', '+12', '625', '1,982', '52', '305', '35', '79,551', '8,235', 'Europe']
['Greece', '2,612', '', '140 ', '', '1,374', '1,098', '36', '251', '13', '77,251', '7,412', 'Europe']
['Oman', '2,483', '+36', '12 ', '+1', '750', '1,721', '17', '486', '2', '40,459', '7,923', 'Asia']
['Afghanistan', '2,469', '+134', '72 ', '+4', '331', '2,066', '7', '63', '2', '11,068', '284', 'Asia']
['Armenia', '2,273', '+125', '33 ', '', '1,010', '1,230', '10', '767', '11', '23,142', '7,810', 'Asia']
['Nigeria', '2,170', '', '68 ', '', '351', '1,751', '2', '11', '0.3', '16,588', '80', 'Africa']
['Ghana', '2,169', '+95', '18 ', '+1', '229', '1,922', '4', '70', '0.6', '113,497', '3,653', 'Africa']
['Iraq', '2,153', '', '94 ', '', '1,414', '645', '', '54', '2', '95,399', '2,372', 'Asia']

['Uzbekistan', '2,094', '+8', '9 ', '', '1,271', '814', '8', '63', '0.3', '242,536', '7,247', 'Asia']
['Croatia', '2,088', '+3', '77 ', '+2', '1,463', '548', '17', '509', '19', '37,557', '9,148', 'Europe']
['Azerbaijan', '1,894', '+40', '25 ', '', '1,411', '458', '17', '187', '2', '152,597', '15,050', 'Asia']
['Bosnia and Herzegovina', '1,839', '+58', '72 ', '+2', '779', '988', '4', '561', '22', '32,783', '9,992', 'Europe']
['Cameroon', '1,832', '', '61 ', '', '934', '837', '12', '69', '2', '', '', 'Africa']
['Iceland', '1,798', '', '10 ', '', '1,706', '82', '', '5,269', '29', '50,002', '146,529', 'Europe']
['Estonia', '1,699', '+5', '53 ', '+1', '256', '1,390', '7', '1,281', '40', '54,464', '41,057', 'Europe']
['Bulgaria', '1,594', '+39', '72 ', '+4', '287', '1,235', '43', '229', '10', '47,636', '6,856', 'Europe']
['Cuba', '1,537', '', '64 ', '', '714', '759', '10', '136', '6', '49,409', '4,362', 'North America']
['Guinea', '1,537', '', '7 ', '', '342', '1,188', '', '117', '0.5', '', '', 'Africa']
['North Macedonia', '1,506', '+12', '82 ', '+1', '852', '572', '21', '723', '39', '16,997', '8,158', 'Europe']
['New Zealand', '1,485', '+6', '20 ', '+1', '1,263', '202', '', '308', '4', '145,589', '30,191', 'Australia/Oceania']
['Slovenia', '1,439', '+5', '94 ', '+2', '239', '1,106', '21', '692', '45', '55,020', '26,465', 'Europe']
['Slovakia', '1,407', '+4', '24 ', '+1', '608', '775', '5', '258', '4', '94,770', '17,358', 'Europe']
['Lithuania', '1,406', '+7', '46 ', '+1', '632', '728', '17', '516', '17', '138,270', '50,792', 'Europe']
['Ivory Coast', '1,333', '', '15 ', '', '597', '721', '', '51', '0.6', '10,073', '382', 'Africa']
['Bolivia', '1,229', '+62', '66 ', '+4', '134', '1,029', '3', '105', '6', '5,791', '496', 'South America']
['Djibouti', '1,112', '+15', '2 ', '', '686', '424', '', '1,126', '2', '13,856', '14,024', 'Africa']
['Hong Kong', '1,040', '', '4 ', '', '864', '172', '4', '139', '0.5', '154,989', '20,674', 'Asia']
['Senegal', '1,024', '', '9 ', '', '356', '659', '1', '61', '0.5', '466', '28', 'Africa']
['Tunisia', '998', '', '41 ', '', '316', '641', '24', '84', '3', '23,526', '1,991', 'Africa']
['Honduras', '899', '+95', '75 ', '', '112', '712', '10', '91', '8', '3,643', '368', 'North America']
['Latvia', '871', '+1', '16  ', '', '348', '507', '2', '462', '8', '63,102', '33,455', 'Europe']
['Cyprus', '857', '', '15 ', '', '296', '546', '15', '710', '12', '60,536', '50,139', 'Asia']
['Albania', '789', '+7', '31 ', '', '519', '239', '4', '274', '11', '8,669', '3,012', 'Europe']
['Kyrgyzstan', '769', '+13', '8 ', '', '527', '234', '12', '118', '1', '51,472', '7,889', 'Asia']
['Andorra', '745', '', '43 ', '', '468', '234', '17', '9,642', '557', '1,673', '21,653', 'Europe']
['Lebanon', '733', '+4', '25 ', '+1', '197', '511', '43', '107', '4', '37,880', '5,550', 'Asia']
['Niger', '728', '', '33 ', '', '478', '217', '', '30', '1', '5,230', '216', 'Africa']
['Costa Rica', '725', '', '6 ', '', '355', '364', '7', '142', '1', '13,529', '2,656', 'North America']
['Diamond Princess', '712', '', '13 ', '', '645', '54', '4', '', '', '', '', '']
['Sri Lanka', '690', '', '7 ', '', '172', '511', '1', '32', '0.3', '23,525', '1,099', 'Asia']
['Burkina Faso', '649', '', '44 ', '', '517', '88', '', '31', '2', '', '', 'Africa']
['Uruguay', '648', '', '17 ', '', '435', '196', '10', '187', '5', '20,554', '5,917', 'South America']
['Guatemala', '644', '+45', '16 ', '', '72', '556', '5', '36', '0.9', '7,200', '402', 'North America']
['DRC', '604', '', '32 ', '', '75', '497', '', '7', '0.4', '', '', 'Africa']
['Somalia', '601', '', '28 ', '', '31', '542', '2', '38', '2', '', '', 'Africa']
['Georgia', '582', '+16', '8 ', '+1', '207', '367', '6', '146', '2', '15,904', '3,987', 'Asia']
['San Marino', '580', '', '41 ', '', '83', '456', '5', '17,094', '1,208', '2,397', '70,643', 'Europe']
['Mayotte', '539', '', '4 ', '', '235', '300', '4', '1,976', '15', '3,000', '10,996', 'Africa']
['Channel Islands', '538', '', '41 ', '', '406', '91', '', '3,094', '236', '5,342', '30,725', 'Europe']
['Sudan', '533', '+91', '36 ', '+5', '46', '451', '', '12', '0.8', '', '', 'Africa']
['Maldives', '514', '+23', '1 ', '', '17', '496', '2', '951', '2', '8,008', '14,815', 'Asia']
['Mali', '508', '', '26 ', '', '196', '286', '', '25', '1', '2,172', '107', 'Africa']
['Tanzania', '480', '', '16 ', '', '167', '297', '7', '8', '0.3', '', '', 'Africa']
['Malta', '468', '+1', '4 ', '', '379', '85', '1', '1,060', '9', '35,117', '79,532', 'Europe']
['Jordan', '459', '', '9  ', '+1', '364', '86', '5', '45', '0.9', '78,885', '7,731', 'Asia']
['El Salvador', '446', '+22', '10 ', '', '138', '298', '2', '69', '2', '26,961', '4,157', 'North America']
['Kenya', '435', '+24', '22 ', '+1', '152', '261', '2', '8', '0.4', '21,702', '404', 'Africa']
['Jamaica', '432', '+10', '8 ', '', '31', '393', '1', '146', '3', '4,779', '1,614', 'North America']
['Taiwan', '432', '+3', '6 ', '', '324', '102', '', '18', '0.3', '63,713', '2,675', 'Asia']
['Réunion', '422', '', ' ', '', '300', '122', '2', '471', '', '', '', 'Africa']
['Palestine', '353', '', '2 ', '', '76', '275', '', '69', '0.4', '32,200', '6,312', 'Asia']
['Venezuela', '335', '', '10 ', '', '148', '177', '2', '12', '0.4', '458,737', '16,132', 'South America']
['Paraguay', '333', '+67', '10 ', '', '115', '208', '5', '47', '1', '10,342', '1,450', 'South America']
['Mauritius', '332', '', '10 ', '', '312', '10', '3', '261', '8', '16,028', '12,603', 'Africa']
['Montenegro', '322', '', '7 ', '', '240', '75', '2', '513', '11', '6,864', '10,929', 'Europe']
['Isle of Man', '320', '+4', '22 ', '', '271', '27', '21', '3,763', '259', '3,242', '38,126', 'Europe']
['Equatorial Guinea', '315', '', '1 ', '', '9', '305', '', '225', '0.7', '854', '609', 'Africa']
['Gabon', '276', '', '3 ', '', '67', '206', '1', '124', '1', '724', '325', 'Africa']
['Vietnam', '270', '', ' ', '', '219', '51', '8', '3', '', '261,004', '2,681', 'Asia']
['Guinea-Bissau', '257', '', '1 ', '', '19', '237', '', '131', '0.5', '1,500', '762', 'Africa']
['Rwanda', '249', '', ' ', '', '109', '140', '', '19', '', '10,969', '847', 'Africa']
['Congo', '229', '', '9 ', '', '25', '195', '', '41', '2', '', '', 'Africa']
['Faeroe Islands', '187', '', ' ', '', '184', '3', '', '3,827', '', '8,021', '164,153', 'Europe']
['Martinique', '179', '', '14 ', '', '83', '82', '5', '477', '37', '', '', 'North America']
['Sierra Leone', '155', '+19', '8 ', '+1', '21', '126', '', '19', '1', '', '', 'Africa']
['Liberia', '152', '', '18 ', '', '45', '89', '', '30', '4', '', '', 'Africa']
['Guadeloupe', '152', '', '12 ', '', '95', '45', '6', '380', '30', '', '', 'North America']
['Myanmar', '151', '', '6 ', '', '37', '108', '', '3', '0.1', '8,281', '152', 'Asia']
['Gibraltar', '144', '', ' ', '', '131', '13', '', '4,274', '', '2,626', '77,944', 'Europe']
['Brunei ', '138', '', '1 ', '', '126', '11', '2', '315', '2', '13,924', '31,828', 'Asia']
['Madagascar', '135', '+3', ' ', '', '97', '38', '1', '5', '', '3,393', '123', 'Africa']
['Ethiopia', '133', '', '3 ', '', '69', '61', '', '1', '0.03', '20,770', '181', 'Africa']
['French Guiana', '128', '', '1 ', '', '98', '29', '2', '429', '3', '', '', 'South America']
['Togo', '123', '', '9 ', '', '66', '48', '', '15', '1', '7,100', '858', 'Africa']
['Cabo Verde', '122', '', '1 ', '', '18', '103', '', '219', '2', '791', '1,423', 'Africa']
['Cambodia', '122', '', ' ', '', '120', '2', '1', '7', '', '12,222', '731', 'Asia']
['Zambia', '119', '+10', '3 ', '', '75', '41', '1', '6', '0.2', '5,284', '287', 'Africa']
['Trinidad and Tobago', '116', '', '8 ', '', '83', '25', '', '83', '6', '1,838', '1,313', 'North America']
['Bermuda', '114', '', '6 ', '', '48', '60', '4', '1,831', '96', '2,791', '44,815', 'North America']
['Eswatini', '108', '+2', '1 ', '', '12', '95', '', '93', '0.9', '714', '615', 'Africa']
['Aruba', '100', '', '2 ', '', '81', '17', '4', '937', '19', '1,721', '16,119', 'North America']
['Monaco', '95', '', '4 ', '', '73', '18', '1', '2,421', '102', '', '', 'Europe']
['Benin', '90', '', '2 ', '', '42', '46', '', '7', '0.2', '', '', 'Africa']
['Haiti', '85', '', '8 ', '', '10', '67', '', '7', '0.7', '848', '74', 'North America']
['Uganda', '85', '', ' ', '', '52', '33', '', '2', '', '33,818', '739', 'Africa']

['Bahamas', '82', '+1', '11 ', '', '24', '47', '1', '209', '28', '1,313', '3,339', 'North America']
['Guyana', '82', '', '9 ', '', '22', '51', '2', '104', '11', '579', '736', 'South America']
['Liechtenstein', '82', '', '1 ', '', '55', '26', '', '2,151', '26', '900', '23,605', 'Europe']
['Barbados', '81', '', '7 ', '', '39', '35', '4', '282', '24', '2,317', '8,063', 'North America']
['Mozambique', '79', '', ' ', '', '18', '61', '', '3', '', '2,246', '72', 'Africa']
['Sint Maarten', '76', '', '13 ', '', '44', '19', '7', '1,773', '303', '329', '7,673', 'North America']
['Cayman Islands', '74', '', '1 ', '', '10', '63', '3', '1,126', '15', '1,927', '29,320', 'North America']
['Chad', '73', '', '5 ', '', '33', '35', '', '4', '0.3', '', '', 'Africa']
['CAR', '72', '', ' ', '', '10', '62', '', '15', '', '', '', 'Africa']
['Libya', '63', '', '3 ', '', '32', '28', '', '9', '0.4', '2,155', '314', 'Africa']
['Nepal', '59', '', ' ', '', '16', '43', '', '2', '', '61,627', '2,115', 'Asia']
['French Polynesia', '58', '', ' ', '', '51', '7', '1', '206', '', '2,599', '9,252', 'Australia/Oceania']
['Macao', '45', '', ' ', '', '37', '8', '1', '69', '', '', '', 'Asia']
['South Sudan', '45', '', ' ', '', '', '45', '', '4', '', '1,247', '111', 'Africa']
['Syria', '44', '', '3 ', '', '27', '14', '', '3', '0.2', '', '', 'Asia']
['Eritrea', '39', '', ' ', '', '26', '13', '', '11', '', '', '', 'Africa']
['Mongolia', '39', '+1', ' ', '', '10', '29', '', '12', '', '8,022', '2,447', 'Asia']
['Saint Martin', '38', '', '3 ', '', '27', '8', '3', '983', '78', '', '', 'North America']
['Malawi', '37', '', '3 ', '', '9', '25', '1', '2', '0.2', '831', '43', 'Africa']
['Zimbabwe', '34', '', '4 ', '', '5', '25', '', '2', '0.3', '7,642', '514', 'Africa']
['Tajikistan', '32', '+17', ' ', '', '', '32', '', '3', '', '', '', 'Asia']
['Angola', '30', '', '2 ', '', '11', '17', '', '0.9', '0.06', '481', '15', 'Africa']
['Antigua and Barbuda', '25', '', '3 ', '', '15', '7', '1', '255', '31', '151', '1,542', 'North America']
['Timor-Leste', '24', '', ' ', '', '16', '8', '', '18', '', '322', '244', 'Asia']
['Botswana', '23', '', '1 ', '', '8', '14', '', '10', '0.4', '7,675', '3,264', 'Africa']
['Grenada', '20', '', ' ', '', '13', '7', '4', '178', '', '1,406', '12,495', 'North America']
['Laos', '19', '', ' ', '', '9', '10', '', '3', '', '2,165', '298', 'Asia']
['Belize', '18', '', '2 ', '', '13', '3', '1', '45', '5', '1,043', '2,623', 'North America']
['Fiji', '18', '', ' ', '', '14', '4', '', '20', '', '1,007', '1,123', 'Australia/Oceania']
['New Caledonia', '18', '', ' ', '', '17', '1', '1', '63', '', '4,947', '17,328', 'Australia/Oceania']
['Saint Lucia', '17', '', ' ', '', '15', '2', '', '93', '', '446', '2,429', 'North America']
['Curaçao', '16', '', '1 ', '', '13', '2', '', '98', '6', '351', '2,139', 'North America']
['Sao Tome and Principe', '16', '', '1 ', '', '4', '11', '', '73', '5', '19', '87', 'Africa']
['Dominica', '16', '', ' ', '', '13', '3', '', '222', '', '383', '5,320', 'North America']
['Namibia', '16', '', ' ', '', '8', '8', '', '6', '', '704', '277', 'Africa']
['St. Vincent Grenadines', '16', '', ' ', '', '8', '8', '', '144', '', '108', '973', 'North America']
['Saint Kitts and Nevis', '15', '', ' ', '', '8', '7', '', '282', '', '294', '5,526', 'North America']
['Nicaragua', '14', '', '3 ', '', '7', '4', '', '2', '0.5', '', '', 'North America']
['Falkland Islands', '13', '', ' ', '', '13', '0', '', '3,736', '', '372', '106,897', 'South America']
['Gambia', '12', '', '1 ', '', '9', '2', '', '5', '0.4', '401', '166', 'Africa']
['Turks and Caicos', '12', '', '1 ', '', '5', '6', '', '310', '26', '83', '2,144', 'North America']
['Burundi', '11', '', '1 ', '', '4', '6', '', '0.9', '0.08', '284', '24', 'Africa']
['Montserrat', '11', '', '1 ', '', '2', '8', '1', '2,204', '200', '36', '7,212', 'North America']
['Greenland', '11', '', ' ', '', '11', '0', '', '194', '', '1,271', '22,389', 'North America']
['Vatican City', '11', '', ' ', '', '2', '9', '', '13,733', '', '', '', 'Europe']
['Seychelles', '11', '', ' ', '', '6', '5', '', '112', '', '', '', 'Africa']
['Suriname', '10', '', '1 ', '', '8', '1', '', '17', '2', '404', '689', 'South America']
['MS Zaandam', '9', '', '2 ', '', '', '7', '', '', '', '', '', '']
['Mauritania', '8', '', '1 ', '', '6', '1', '', '2', '0.2', '1,032', '222', 'Africa']
['Papua New Guinea', '8', '', ' ', '', '', '8', '', '0.9', '', '604', '68', 'Australia/Oceania']
['Yemen', '7', '', '2 ', '', '1', '4', '', '0.2', '0.07', '120', '4', 'Asia']
['Bhutan', '7', '', ' ', '', '5', '2', '', '9', '', '10,548', '13,670', 'Asia']
['British Virgin Islands', '6', '', '1 ', '', '3', '2', '', '198', '33', '', '', 'North America']
['Caribbean Netherlands', '6', '', ' ', '', '', '6', '', '229', '', '110', '4,195', 'North America']
['St. Barth', '6', '', ' ', '', '6', '0', '', '607', '', '', '', 'North America']
['Western Sahara', '6', '', ' ', '', '5', '1', '', '10', '', '', '', 'Africa']
['Anguilla', '3', '', ' ', '', '3', '0', '', '200', '', '', '', 'North America']
['Comoros', '1', '', ' ', '', '', '1', '', '1', '', '', '', 'Africa']
['Saint Pierre Miquelon', '1', '', ' ', '', '', '1', '', '173', '', '', '', 'North America']
['China', '82,875', '+1', '4,633 ', '', '77,685', '557', '37', '58', '3', '', '', 'Asia']
['Total:', '1,229,885', '+4,930', '72,032', '+252', '201,020', '956,833', '17,724', '', '', '', '', 'North America']
['Total:', '1,415,503', '+16,813', '138,018', '+609', '528,830', '748,655', '17,831', '', '', '', '', 'Europe']
['Total:', '540,122', '+6,281', '19,123', '+162', '278,344', '242,655', '5,534', '', '', '', '', 'Asia']
['Total:', '190,749', '+650', '9,512', '+32', '63,943', '117,294', '9,816', '', '', '', '', 'South America']
['Total:', '8,370', '+22', '113', '+1', '7,134', '1,123', '30', '', '', '', '', 'Australia/Oceania']
['Total:', '41,817', '+377', '1,700', '+9', '14,138', '25,979', '126', '', '', '', '', 'Africa']
['Total:', '721', '', '15', '', '645', '61', '4', '', '', '', '', '']
['Total:', '3,427,167', '+29,073', '240,513', '+1,065', '1,094,054', '2,092,600', '51,065', '439.7', '30.9', '', '', 'All']

In [4]:
full_data.head(10)

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop
0,World,3427167,"+29,073",240513.0,"+1,065",1094054.0,2092600,51065.0,440.0,30.9,NaN,NaN
1,USA,1134084,"+3,054",65888.0,+135,161782.0,906414,16481.0,3426.0,199.0,6715433.0,20288.0
2,Spain,245567,"+2,588",25100.0,+276,146233.0,74234,2386.0,5252.0,537.0,1528833.0,32699.0
3,Italy,207428,NaN,28236.0,NaN,78249.0,100943,1578.0,3431.0,467.0,2053425.0,33962.0
4,UK,177454,NaN,27510.0,NaN,NaN,149600,1559.0,2614.0,405.0,1023824.0,15082.0
5,France,167346,NaN,24594.0,NaN,50212.0,92540,3878.0,2564.0,377.0,1100228.0,16856.0
6,Germany,164271,+194,6736.0,NaN,129000.0,28535,2189.0,1961.0,80.0,2547052.0,30400.0
7,Russia,124054,"+9,623",1222.0,+53,15013.0,107819,2300.0,850.0,8.0,3945518.0,27036.0
8,Turkey,122392,NaN,3258.0,NaN,53808.0,65326,1480.0,1451.0,39.0,1075048.0,12747.0
9,Iran,96448,+802,6156.0,+65,77350.0,12942,2787.0,1148.0,73.0,484541.0,5769.0

### Covid_19 India CSV file :
- Confirmed cases, Deaths, Cured cases.

In [31]:
covid_19_india_url = "https://api.covid19india.org/states_daily.json"
#https://api.covid19india.org/state_district_wise.json
#https://api.covid19india.org/states_daily.json
#https://api.covid19india.org/state_test_data.json

req_data = requests.get(covid_19_india_url)
j =req_data.json()
train = pd.DataFrame(j['states_daily'])
#j
# json = req_data.json()
# normJson = json_normalize(json)
# df = pd.DataFrame(normJson)
train

,an,ap,ar,as,br,ch,ct,date,dd,dl,...,rj,sk,status,tg,tn,tr,tt,up,ut,wb
0,0,1,0,0,0,0,0,14-Mar-20,0,7,...,3,0,Confirmed,1,1,0,81,12,0,0
1,0,0,0,0,0,0,0,14-Mar-20,0,1,...,1,0,Recovered,0,0,0,9,4,0,0
2,0,0,0,0,0,0,0,14-Mar-20,0,1,...,0,0,Deceased,0,0,0,2,0,0,0
3,0,0,0,0,0,0,0,15-Mar-20,0,0,...,1,0,Confirmed,2,0,0,27,1,0,0
4,0,0,0,0,0,0,0,15-Mar-20,0,1,...,2,0,Recovered,1,0,0,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,1,34,0,0,20,1,2,30-Apr-20,0,2,...,79,0,Recovered,33,48,0,630,41,8,5
143,0,0,0,0,0,0,0,30-Apr-20,0,3,...,3,0,Deceased,3,0,0,75,1,0,11
144,0,60,0,0,41,14,3,01-May-20,0,223,...,82,0,Confirmed,6,203,0,2381,117,0,37
145,0,82,0,4,14,0,0,01-May-20,0,73,...,223,0,Recovered,22,54,0,961,103,1,15
146,0,2,0,0,1,0,0,01-May-20,0,2,...,4,0,Deceased,0,1,0,69,2,1,0

In [ ]:
# html = driver.page_source
# soup = BeautifulSoup(html)
# driver = webdriver.Googlechrome()
# driver.get("https://www.covid19india.org/" )

# html = driver.page_source
# html
#url = "https://www.covid19india.org/" 

#req_data = requests.get(url)
#req_data.text
# soup = BeautifulSoup(req_data.text, 'html.parser') 
# soup
# #soup.find_all('h')
# x = soup.findAll("tbody")

# if x is not None and len(x) > 0:
#     section = x[0]
# table = soup.findAll("table")

# table
#table = soup.find('table', attrs={'id': 'main_table_countries_today'})
# header = [col_name.text.rstrip('\n').strip() for col_name in table.select('thead th')]
# table_rows = table.find_all('tr')
# data = []
# for tr in table_rows:
#     try: 
#         td = tr.find_all('td')
#         row = [tr.text for tr in td]
#         print(row) 
#         data.append(row)
#         full_data = pd.read_html(str(table))[0]
#     except requests.Response.raise_for_status() as e:
#         print("Error: Invalid Response Error.")
# #data = [[td.getText() for td in data[i].find_all(['td','th'])] for i in range(len(data))]
# #full_data = pd.read_html(str(table))[0]

# #full_data = pd.DataFrame(data, columns=["A", "B", ...])

In [34]:
covid_india = pd.read_csv('covid_19_india.csv')

In [35]:
covid_india.head(5)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3

In [ ]:
covid_india_age = pd.read_csv('AgeGroupDetails.csv')
covid_india_age

In [ ]:
covid_india_testing = pd.read_csv('ICMRTestingDetails.csv')
covid_india_testing

### Covid_19 India CSV file :
- CSV contain Statewise Testing Positive and Negative Patients data.

In [ ]:
covid_india_state_testing = pd.read_csv('StatewiseTestingDetails.csv')
covid_india_state_testing

#### Time Series Covid_19 case Csv file :
-TimeSeries data contain DATE and Country information.

In [ ]:
covid_time_series_C= pd.read_csv('time_series_covid19_confirmed.csv')
covid_time_series_C

In [ ]:
covid_time_series_covid_19_R = pd.read_csv('time_series_covid19_recovered.csv')
covid_time_series_covid_19_R

In [ ]:
covid_time_series_D = pd.read_csv('time_series_covid19_deaths.csv')
covid_time_series_D

#### Assessing of Data:

****Assessing Full_data of covid_19 all countries Data

In [ ]:
full_data.info()

The coronavirus COVID-19 is affecting 212 countries and territories around the world and 2 international conveyances are reported in www.worldometers.info/coronavirus/.
 1.Total 216 countries only 177 countries reported deaths.
 2 TotalRecovered cases reported in 207 countries.
 3.61 NewDeaths are reported.
 4.Testing reported in 177 countries.
** Some data is missing but can't analyze missing data may be  True or confirmed cases,deaths,Recovered cases are not reported .

#### Data Issue 1:
***Rename Columns:

In [ ]:
full_data.rename(columns = lambda X:X.strip().lower().replace(" ","_"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("country,other","country"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("totalcases","total_cases"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("newcases","new_cases"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("totaldeaths","total_deaths"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("newdeaths","new_deaths"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("totalrecovered","total_recovered"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("activecases","active_cases"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("serious,critical","serious"),inplace =True)
full_data.rename(columns = lambda X:X.strip().lower().replace("totaltests","total_tests"),inplace =True)

In [ ]:
full_data.rename(columns = lambda X:X.strip().lower().replace("tot cases/1m_pop","totcases/1m_pop"),inplace =True)

#### Data Issue 2:
##### Fill NaN with zero value:

In [ ]:
full_data.fillna(0, inplace=True)

#### Data Issue 4:
    datatype Object is converted into integer value datatype
#### Data  issues:3
    Replace comma,plussign from all the value in dataframe column.

In [ ]:
full_data['total_deaths'] = full_data['total_deaths'].astype('int64')
full_data['total_recovered'] = full_data['total_recovered'].astype('int64')
full_data['serious'] = full_data['serious'].astype('int64')
full_data['deaths/1m_pop'] = full_data['deaths/1m_pop'].astype('int64')
full_data['total_tests'] = full_data['total_tests'].astype('int64')
full_data['tests/_1m_pop'] = full_data['tests/_1m_pop'].astype('int64')

In [ ]:
full_data['new_cases'] = full_data['new_cases'].str.replace(',', '', regex=True)
full_data['new_deaths'] = full_data['new_deaths'].str.replace(',','', regex=True)
full_data

In [ ]:
full_data['new_cases'] = full_data['new_cases'].str.replace('+','', regex=True)
full_data['new_deaths'] = full_data['new_deaths'].str.replace('+','', regex=True)
full_data['new_cases'].fillna(0,inplace=True)
full_data['new_deaths'].fillna(0,inplace=True)
full_data['new_cases'] = full_data['new_cases'].astype('int64')
full_data['new_deaths'] = full_data['new_deaths'].astype('int64')
full_data.info()

In [ ]:
###full_data['tot cases/1m_pop'] = full_data['tot cases/1m_pop'].str.replace('+','', regex=True)

####full_data['tot cases/1m_pop'] = full_data['tot cases/1m_pop'].astype('int64')

In [ ]:
##full_data['totcases/1m_pop'] = full_data['totcases/1m_pop'].replace({'/': ''}, regex=True)
##full_data.head(1)
##full_data['totcases/1m_pop'] = full_data['totcases/1m_pop'].astype('int64')

In [ ]:
full_data.describe()

In [ ]:
full_data.sum()

In [ ]:
full_data.total_cases.max()

In [ ]:
full_data.total_deaths.max()

In [ ]:
full_data.total_recovered.max()

In [ ]:
full_data.duplicated().sum()

In [ ]:
full_data.isna().sum()

In [ ]:
full_data['country'].value_counts()

In [ ]:
full_data.country.nunique()

**** Assessing Data of covid_19 India Data .

In [ ]:
#covid_india.info()

In [ ]:
#covid_india.describe()

In [ ]:
#covid_india.sum()

In [ ]:
#covid_india['State/UnionTerritory'].value_counts()

In [ ]:
#covid_india.duplicated().sum()

In [ ]:
#covid_india.isna().sum()

In [ ]:
#covid_india.Deaths.max()

In [ ]:
#covid_india['State/UnionTerritory'].unique()

In [ ]:
#covid_india_state_testing.sum()

In [ ]:
#covid_india_state_testing.duplicated().sum()

In [ ]:
#covid_india_state_testing.isna().sum()

In [ ]:
#covid_india_state_testing.describe()

 ConfirmedIndianNational,ConfirmedForeignNational datatype object value.

********Assessing time_series Data of covid_19 All Countries Data .

In [ ]:
#covid_time_series_C.info()

In [ ]:
#covid_time_series_covid_19_R.info()

In [ ]:
#covid_time_series_D.info()

In [ ]:
#covid_time_series_C.isna().sum()

In [ ]:
#covid_time_series_covid_19_R.isna().sum()

In [ ]:
#covid_time_series_D.isna().sum()

In [ ]:
#covid_time_series_C.describe()

In [ ]:
#covid_time_series_covid_19_R.describe()

In [ ]:
#covid_time_series_D.describe()

#### Data Issue 5:
***Drop [Sno.] from column in Covid_india_age dataframe.

In [ ]:
covid_india_age = covid_india_age.drop(['Sno'], axis=1)

In [ ]:
#covid_india_age

*** Covid_india['State/UnionTerritory']csv file assign the value in nagaland two time .these issue is negelected for analysis .

#### Data Issue 6:
*** Missing value (Nan)in 3 covid_time_series dataframe:Confirmed,Recovered,Death.

In [ ]:
covid_time_series_covid_19_R.fillna(0, inplace=True)

In [ ]:
covid_time_series_C.fillna(0,inplace = True)

In [ ]:
covid_time_series_D.fillna(0,inplace =True)

#### Data Issue 7:
***Drop [province/stste, lat,long] from column in Covid time_series dataframe.

In [ ]:
covid_time_series_covid_19_R = covid_time_series_covid_19_R.drop(['Province/State','Lat','Long'], axis=1)
#covid_time_series_covid_19_R

In [ ]:
covid_time_series_C =covid_time_series_C.drop(['Province/State','Lat','Long'], axis=1)
#covid_time_series_C

In [ ]:
covid_time_series_D = covid_time_series_D.drop(['Province/State','Lat','Long'], axis=1)
#covid_time_series_D

#### Data Issue 8:
***  Difficult to analyze time_series data. In this dataframe analysis melt funtion is  used .Unpivot date columns[2:] with variable column ‘Date’ and value column ‘Confirmed’,'Recovered','Death'

In [ ]:
dates = covid_time_series_C.columns[2:]
covid_time_series_C = covid_time_series_C.melt(
    id_vars=['Country/Region'], 
    value_vars=dates, 
    var_name='Date', 
    value_name='Confirmed'

)

covid_time_series_C

In [ ]:
dates = covid_time_series_D.columns[2:]
covid_time_series_D = covid_time_series_D.melt(
    id_vars=['Country/Region'], 
    value_vars=dates, 
    var_name='Date', 
    value_name='Deaths'
)

#covid_time_series_D

In [ ]:

dates = covid_time_series_covid_19_R.columns[2:]
covid_time_series_covid_19_R= covid_time_series_covid_19_R.melt(
    id_vars=['Country/Region'], 
    value_vars=dates, 
    var_name='Date', 
    value_name='Recovered'
)

#covid_time_series_covid_19_R

#### Data Issue 9:
*Merge the Covid_time_series_C,Covid_time_series_D,Covid_time_series_covid_19_R using merge function.
*Calculate Death_percentage and Recovered_percentage in Covid_time_series dataframe.

In [ ]:
covid_time_series= covid_time_series_C.merge(right=covid_time_series_D, how='left',on=['Country/Region', 'Date'])
covid_time_series = covid_time_series.merge( right=covid_time_series_covid_19_R, how='left',on=['Country/Region', 'Date'])
covid_time_series['Death_percentage'] = (covid_time_series.Deaths / covid_time_series.Confirmed)/100
covid_time_series['Recovered_percentage'] = (covid_time_series.Recovered / covid_time_series.Confirmed)/100
#covid_time_series

#### Data Issue10:
*** Replace NaN value with Zero in Death_Percentage ,Recovered_percentage in covid_time_series.

In [ ]:
covid_time_series.fillna(0, inplace=True)

In [ ]:
covid_time_series['Date'] = pd.to_datetime(covid_time_series['Date'], errors='coerce')
covid_time_series['Day'] = covid_time_series['Date'].dt.day
#covid_time_series['Day']

*** Store Covid_time_sereies data in New csv file:

In [ ]:
covid_time_series.to_csv('covid_time_series1.csv')

In [33]:
covid_time_series_I = covid_time_series[covid_time_series['Country/Region']=='India']
covid_time_series_I.head(5)

NameError: name 'covid_time_series' is not defined

### Exploratory data analysis (EDA)
 
######### Covid_19 All countries Data:
Determine mortality rates and recovered cases of covid 19,Analysis is based on the number of excess deaths in different countries and predicted the mortality and Recovered patients in different country.

In [ ]:
full_data.head(2)

***Total Deaths Cases in World

In [ ]:
# fig = px.scatter(full_data,x="total_cases",y="total_deaths",text="country",log_x=True ,log_y=True ,size_max=100, range_x=[1,1000000000],range_y=[1,1000000])
# fig.update_traces(textposition='top center')
# fig.update_layout(
#     height=800,width=1000,
#     title_text='Total Deaths Cases in the world',xaxis = dict(
#         tickangle = 90,
#         title_text = "Total_cases",
#         title_font = {"size": 15},
#         title_standoff = 10),
#     yaxis = dict(
#         title_text = "Total_Deaths Cases",
#         title_standoff = 10)
# )
# fig.show()

- Total Deaths Reported in many countries below 1000 and

***Total Recovered Cases in World

In [ ]:
# fig = px.scatter(full_data,x="total_cases",y="total_recovered", text="country",  log_x=True ,log_y=True ,size_max=100, range_x=[1,10000000],range_y=[1,1000000])
# fig.update_traces(textposition='top center')
# fig.update_layout(
#     height=800,width=1000,
#     title_text='Total Recovered Cases in the world',
#     xaxis = dict(
#         tickangle = 90,
#         title_text = "Total_cases",
#         title_font = {"size": 15},
#         title_standoff = 10),
#     yaxis = dict(
#         title_text = "Total_recovered Cases",
#         title_standoff = 10)

# )
# fig.show()

**** here all countries is consider for analysis so, there is overlapping in scatter plot.

### Analysis of Covid_19 Cases in All countries Based on Statsmodel:
-Statsmodels module is used for covid_19 cases that provides classes and functions for the estimation  regression models,for conducting statistical tests, and statistical data exploration of covid_19('total_cases','total_deaths','new_cases','new_deaths','total_recovered','active_cases')in all countries.

In [ ]:
X = full_data[['total_deaths','new_cases','new_deaths']] 
# #### fit a OLS model with intercept on total_cases and  new_cases,new_deaths.
y = full_data['total_cases']
X = sm.add_constant(X)
est = sm.OLS(y, X).fit()
print(est.summary())

From our results, we see that
• The intercept 𝛽̂0 = -151.83.

• The slope 𝛽̂1 = 12.

• The positive 𝛽̂1 parameter estimate implies that        has a positive effect on          , as in the figure.

• The p-value of total_deaths and new_cases,new_deaths 0.000 for 𝛽̂1implies that is statisticallysignificant (using p < 0.05 as a rejection rule).

• The R-squared value of R-squared: 0.997  indicates that around   of variation in                   is explained by protection against            .

In [ ]:
# fig = plt.figure(figsize =(15,8))
# results = smf.ols('total_cases~total_deaths+new_cases+new_deaths', data = full_data).fit()
# #sm.graphics.plot_ccpr_grid(results, fig=fig)
# sm.graphics.plot_regress_exog(results, 'total_deaths', fig=fig)
# plt.show()

In [ ]:
# X = full_data[['total_recovered','new_cases','active_cases']] 
# #### fit a OLS model with intercept on total_recovered and  new_cases,active_cases.
# y = full_data['total_cases']
# X = sm.add_constant(X)
# est = sm.OLS(y, X).fit()
#print(est.summary())

In [ ]:
# fig = plt.figure(figsize =(15,8))
# results = smf.ols('total_cases~total_recovered  + new_cases+active_cases', data = full_data).fit()
# #sm.graphics.plot_ccpr_grid(results, fig=fig)
# sm.graphics.plot_regress_exog(results, 'total_recovered', fig=fig)
# plt.show()

### Analysis of Covid_19  Total_cases ,Active_Case, Serious Cases  in All countries.

In [ ]:
fig = px.scatter(full_data, y='total_cases', x='activses',animation_frame="active_cases",animation_group="total_cases" ,color='country',text = "country",range_x =[0,100000],range_y=[0,100000])
fig2 = px.scatter(full_data, y='total_cases', x='serious', animation_frame="serious", animation_group="total_cases",color='country',range_x =[0,10000],range_y=[0,100000]) 
fig.show()
fig2.show()

### Analysis of Covid_19  Totcase/1Mpop,Deaths/1Mpop,Tests/1Mpop in All countries.

In [ ]:
# fig = px.scatter(full_data, y='totcasespopm', x='deathspopm', color='country',log_x=True ,log_y=True ,size_max=45)
# fig2 = px.scatter(full_data, y='totcasespopm', x='testspopm', color='country',log_x=True ,log_y=True ,size_max=45) 
# fig.show()
# fig2.show()

In [ ]:
#full_data=full_data.melt( id_vars=['country'], value_vars=['total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'total_recovered','active_cases','serious','totcasespopm','deathspopm','deathspopm','testspopm'])
# full_data=pd.melt(full_data, id_vars=['country'], value_vars=['total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'total_recovered'])

# # plotly 
# fig = px.line(full_data, x='country', y='value', color='variable',log_x=False ,log_y=True)

# # Show plot 
# fig.show()

Exploratory data analysis (EDA) INDIA:
######### Covid_19 Cases in India:
Determine mortality rates and Cured cases of covid 19,Analysis is based on the number of excess deaths in India and predicted the mortality and Recovered patients in State and Union Territory .

### Univariate analysis:

In [ ]:
# base_color = sns.color_palette()[1]
# plt.figure(figsize=(32,6))
# g = sns.countplot(data = covid_india, x ='State/UnionTerritory', color = base_color)
# g.set_xticklabels(g.get_xticklabels(), rotation=45)
# n_points = covid_india.shape[0]
# cat_counts = covid_india['State/UnionTerritory'].value_counts()
# locs, labels = plt.xticks() 
# for loc, label in zip(locs, labels):
#     count = cat_counts[label.get_text()]
#     pct_string = '{:0.1f}%'.format(100*count/n_points)
#     plt.text(loc, count-8, pct_string, ha = 'left',va='bottom', color = 'black')

### BiVariate Analysis of Covid_19 Cases in  India:

In [ ]:
# fig = px.scatter(covid_india,x="Confirmed",y="Deaths" ,animation_frame="Deaths", animation_group="State/UnionTerritory",color="State/UnionTerritory",log_x=True ,log_y=True , range_x=[1,10000],range_y=[1,10000])
# fig.update_traces(textposition='top center')

# fig.update_layout(
#     height=800,width=1000,
#     title_text='Total Deaths Cases in India',xaxis = dict(
#         tickangle = 90,
#         title_text = "Total_cases",
#         title_font = {"size": 15},
#         title_standoff = 10),
#     yaxis = dict(
#         title_text = "Total_Deaths Cases",
#         title_standoff = 10),
    
# )

# fig.show()

In [ ]:

# fig = px.scatter(covid_india,x="Confirmed",y="Cured", animation_frame="Cured", animation_group="State/UnionTerritory",color="State/UnionTerritory", log_x=True ,log_y=True ,size_max=45, range_x=[1,10000],range_y=[1,10000])
# fig.update_traces(textposition='top center')

# fig.update_layout(
#     height=800,width=1000,
#     title_text='Total Recovered Cases in India',xaxis = dict(
#         tickangle = 90,
#         title_text = "Total_cases",
#         title_font = {"size": 15},
#         title_standoff = 10),
#     yaxis = dict(
#         title_text = "Total Recovered Cases",
#         title_standoff = 10)
# )


# fig.show()

### Analysis of Covid_19 Cases in  India Based on StatsModel:
-Statsmodels module is used for covid_19 cases that provides classes and functions for the estimation  regression models,for conducting statistical tests, and statistical data exploration of covid_19('Confirmed cases','Deaths cases','Cured cases')in india.

In [ ]:
# X = covid_india[['Deaths']] 
# #### fit a OLS model with intercept on Deaths
# y = covid_india['Confirmed']
# X = sm.add_constant(X)
# est = sm.OLS(y, X).fit()
# print(est.summary())

In [ ]:

# fig = plt.figure(figsize =(15,8))
# #full_data1= sm.dataset.full_data.load_pandas()
# results = smf.ols('Confirmed ~Deaths ', data = covid_india).fit()
# #sm.graphics.plot_ccpr_grid(results, fig=fig)
# sm.graphics.plot_regress_exog(results, 'Deaths', fig=fig)
# plt.show()

In [ ]:
# X = covid_india[['Cured']] 
# #### fit a OLS model with intercept on Cured Cases
# y = covid_india['Confirmed']
# X = sm.add_constant(X)
# est = sm.OLS(y, X).fit()
# print(est.summary())

In [ ]:
# fig = plt.figure(figsize =(15,8))
# #full_data1= sm.dataset.full_data.load_pandas()
# results = smf.ols('Confirmed ~Cured', data = covid_india).fit()
# #sm.graphics.plot_ccpr_grid(results, fig=fig)
# sm.graphics.plot_regress_exog(results, 'Cured', fig=fig)
# plt.show()

###Note: Points to understand Residual value more clearly in any Regression graph :
-Residuals. The difference between the observed value of the dependent variable (y) and the predicted value (ŷ) is called the residual (e). Each data point has one residual. Both the sum and the mean of the residuals are equal to zero.
-Residual analysis is used to assess the appropriateness of a linear regression model by defining residuals and examining the residual plot graphs.
-residual values should be equally and randomly spaced around the horizontal axis. If your plot looks like any of the following images, then your data set is probably not a good fit for regression. A non-linear pattern.
-A residual plot has the Residual Values on the vertical axis; the horizontal axis displays the independent variable. A residual plot is typically used to find problems with regression. Some data sets are not good candidates for regression, including: ... Data that is non-linearly associated.

### Analysis of Covid_19 Cases in  India and its State /Union Territory :

In [ ]:
# f,g = plt.subplots(figsize = (15,10))
# base_color = sns.color_palette()[0]
# g = sns.barplot(data = covid_india, x = 'Confirmed', y = 'State/UnionTerritory',
#             label = 'Total Confirmed Cases',color = base_color)
# sns.set_color_codes('muted')
# g = sns.barplot(x = 'Cured', y = 'State/UnionTerritory', data = covid_india,
#             label = 'Total number of Cured', color = 'R', edgecolor = 'w')
# sns.set_color_codes('pastel')
# g= sns.barplot(x = 'Deaths', y = 'State/UnionTerritory', data = covid_india,
#             label = 'Total number of Deaths', color = 'g', edgecolor = 'w')
# g.legend(ncol = 3, loc = 'lower right')
# #sns.despine(left = True, bottom = True)
# plt.show()

Manipur ,Mizoram ,Arunachal Pradesh, Tripura , Nagaland confirmed cases not reported Yet ..

### Analysis of Covid_19 Cases in  India and its State /Union Territory

In [ ]:
# plt.figure(2, figsize=(20,15))
# fig,ax = plt.subplots(1, 2)
# g =sns.scatterplot(data=covid_india,y="Deaths",x="Confirmed",ax=ax[0],hue="State/UnionTerritory",palette="deep")
# g.legend(loc='upper right', bbox_to_anchor=(.20, 0.0), ncol=1)
# g =sns.scatterplot(data=covid_india,y="Cured",x="Confirmed",ax=ax[1],hue="State/UnionTerritory",palette="deep")
# g.legend(loc='upper left', bbox_to_anchor=(1.0, 0.0), ncol=1)

### Analysis Based on Age group in india

In [ ]:

# fig = px.bar(covid_india_age, y='TotalCases', x='AgeGroup', text='Percentage')
# fig.update_traces(texttemplate='%{text}', textposition='outside',marker_color='lightsalmon')
# fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')
# fig.show()

In [ ]:
# s = covid_india_state_testing.sum()
# s

### Analysis of Covid_19 Cases Based  on  Testing (Positive Cases and Negative Case) in  India :

In [ ]:
# fig = px.scatter(covid_india_state_testing, x='Date', y='Positive', title='Positive Cases Time Series with Rangeslider',range_x=['1/23/20','4/27/20'],range_y = [1,15000])
# fig.update_traces(marker_color='indianred')
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()
# fig1 = px.scatter(covid_india_state_testing, x='Date', y='Negative', title='Negative Cases Time Series with Rangeslider',range_x=['1/23/20','4/27/20'],range_y = [1,50000])
# fig1.update_traces(marker_color='lightsalmon')
# fig1.update_xaxes(rangeslider_visible=True)
# # fig1.show()

## Covid_Time_Series Analysis: Datewise Confirmed Cases,Deaths, Recovered Cases in All Countries :
Date:22/jan/2020 till 29/April/2020

In [ ]:
# fig = px.scatter(covid_time_series_C, x='Date', y='Confirmed',color="Country/Region", title='Confirmed Cases Time Series with Rangeslider',range_x=['1/22/20','4/29/20'],range_y = [1,1000000])
# fig.update_traces(marker_color='darkslateblue')
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()

In [ ]:
# fig = px.scatter(covid_time_series_D, x='Date', y='Deaths',color="Country/Region", title='Deaths Cases Time Series with Rangeslider',range_x=['1/22/20','4/29/20'],range_y = [1,100000])
# fig.update_traces(marker_color='sandybrown')
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()

In [ ]:
# fig = px.scatter(covid_time_series_covid_19_R, x='Date', y='Recovered',color="Country/Region", title='Recovered Cases Time Series with Rangeslider',range_x=['1/22/20','4/29/20'],range_y = [1,100000])
# fig.update_traces(marker_color='green')
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()

In [ ]:

# fig = px.scatter(covid_time_series_covid_19_R, x='Date', y='Recovered',color="Country/Region", title='Recovered Cases Time Series with Rangeslider',range_x=['1/23/20','4/19/20'],range_y = [1,100000])
# fig.update_traces(marker_color='green')
# fig.update_xaxes(rangeslider_visible=True)
# fig.show()# # Plot 
# fig = px.scatter(covid_time_series, x='Day', y='Confirmed',color="Country/Region",log_x=False ,log_y=True ) 
# fig.show()
# fig1 = px.scatter(covid_time_series, x='Day', y='Deaths',color="Country/Region",log_x=False ,log_y=True ) 
# fig1.show()
# fig2 = px.scatter(covid_time_series, x='Day', y='Recovered',color="Country/Region",log_x=False ,log_y=True )
# fig2.show()

In [ ]:
covid_time_series.head(5)

In [ ]:

fig = px.choropleth(full_data, locations=full_data["country"],color='total_cases',
                    color_continuous_scale=px.colors.sequential.Viridis,hover_name="country",animation_frame=full_data["total_deaths"],
                
                   )
                                          
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.update_layout(transition = {'duration':10000})
fig.show()

In [ ]:
fig = px.choropleth(full_data, locations='total_cases', color='total_deaths',
                           color_continuous_scale="Viridis",animation_frame=full_data["total_cases"],
                           range_color=(0, 12),
                           scope="asia"
                           
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:

fig = px.scatter_geo(full_data, locations="country",color = 'country',
                    color_continuous_scale=px.colors.sequential.Viridis,
                     hover_name="country",size='total_cases',
                     animation_frame='total_deaths',
                     projection="natural earth"
                
                   )
for i in range(6,10)[::-1]:
     fig.add_trace(go.Scattergeo(
            lon = full_data['long'],
            lat = full_data['lat'],
            text = ['country'],
            mode = 'text',
            showlegend = False,
            #geo = 'geo2'
                  ))
                                                                            
fig.show()
                                          
#fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
#fig.update_layout(transition = {'duration':10000})

In [ ]:
fig = px.scatter_geo(full_data, locations='total_cases', color='total_deaths',
                           color_continuous_scale="Viridis",animation_frame=full_data["total_deaths"],
                           range_color=(0, 12),
                           scope="asia"
                           
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

#### Conclusion: 
#######Analyze curated data related to the Covid_19 Viral Disease  to understand the magnitude of the risk posed by this infectious Disease in all Countries:
     - First cases of covid_19 is reported in Wuhan (the city where the virus originated)Central China, with a population of          over 11 million people.The city, on January 23.
     - 2-14 days represents the current official estimated range for the novel coronavirus COVID-19.
     - On January Month , the novel coronavirus cases in the UK,Russia,Sweden, Spain were reported less in number.
     - On March and April Months there is tremendous increase of Confirmed cases and Deaths Cases in all over World.
       ** Total Confirmed Case in World = 
       ** Total Deaths Case in World = 
       ** Total Recovered Case in World=
       ** Total Confirmed Case in India = 
       ** Total Deaths Case in India = 
       ** Total Recovered Case in India =
       
    - Age and conditions of Coronavirus cases in india  reported 
    - India Testing data Total Sample =          ,Negative Sample=          ,Positive Sample =

In [ ]:
### Reference:
1.
2.
3.